trigger:
- master

jobs:

- job: 'Test'
  displayName: 'Test'

  strategy:
    matrix:
      LinuxNode8:
        imageName: 'ubuntu-16.04'
        nodeVersion: '8'
        hasWebGLTesting: false
      LinuxNode11:
        imageName: 'ubuntu-16.04'
        nodeVersion: '11'
        hasWebGLTesting: false
      macOSNode8:
        imageName: 'macos-10.13'
        nodeVersion: '8'
        hasWebGLTesting: false
      macOSNode11:
        imageName: 'macos-10.13'
        nodeVersion: '11'
        hasWebGLTesting: false
      WindowsNode8:
        imageName: 'vs2017-win2016'
        nodeVersion: '8'
        hasWebGLTesting: false
      WindowsNode11:
        imageName: 'vs2017-win2016'
        nodeVersion: '11'
        hasWebGLTesting: false

  pool:
    imageName: $(imageName)

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion).x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build'

  - bash: |
      if $(hasWebGLTesting); then
        npm run test
      else
        echo "Testing skipped because there is no WebGL environment."
      fi
    displayName: 'Test'
