name: Release
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm ci
          sudo apt-get install xvfb

      - name: Setup ipfs
        uses: ibnesayeed/setup-ipfs@master
        with:
          ipfs_version: ^0.12
      - name: Connect to ipfs peers with our data
        shell: bash
        run: |
          export MSYS_NO_PATHCONV=1
          # web3.storage
          ipfs swarm connect /ip4/139.178.69.155/tcp/4001/p2p/12D3KooWR19qPPiZH4khepNjS3CLXiB7AbrbAD4ZcDjN1UjGUNE1
          ipfs swarm connect /ip4/139.178.68.91/tcp/4001/p2p/12D3KooWEDMw7oRqQkdCJbyeqS5mUmWGwTp8JJ2tjCzTkHboF6wK
          ipfs swarm connect /ip4/147.75.33.191/tcp/4001/p2p/12D3KooWPySxxWQjBgX9Jp6uAHQfVmdq8HG1gVvS1fRawHNSrmqW
          ipfs swarm connect /ip4/147.75.32.73/tcp/4001/p2p/12D3KooWNuoVEfVLJvU3jWY2zLYjGUaathsecwT19jhByjnbQvkj
          ipfs swarm connect /ip4/145.40.89.195/tcp/4001/p2p/12D3KooWSnniGsyAF663gvHdqhyfJMCjWJv54cGSzcPiEMAfanvU
          ipfs swarm connect /ip4/136.144.56.153/tcp/4001/p2p/12D3KooWKytRAd2ujxhGzaLHKJuje8sVrHXvjGNvHXovpar5KaKQ
          # pinata.cloud
          ipfs swarm connect /dnsaddr/nyc1-1.hostnodes.pinata.cloud/p2p/QmRjLSisUCHVpFa5ELVvX3qVPfdxajxWJEHs9kN3EcxAW6
          ipfs swarm connect /dnsaddr/nyc1-2.hostnodes.pinata.cloud/p2p/QmPySsdmbczdZYBpbi2oq2WMJ8ErbfxtkG8Mo192UHkfGP
          ipfs swarm connect /dnsaddr/nyc1-3.hostnodes.pinata.cloud/p2p/QmSarArpxemsPESa6FNkmuu9iSE1QWqPX2R3Aw6f5jq4D5
      - name: Pin ipfs testing data locally
        shell: bash
        run: |
          cid=$(grep 'IPFS_CID =' test/downloadData.mjs | cut -d ' ' -f 4 | tr -d "'")
          ipfs get -o ./test/data -- $cid

      - name: Build
        run: npm run build
      - name: Chrome and Firefox tests
        run: |
          # Failing based on vtk.js piecewisegaussian?
          # xvfb-run --auto-servernum npm run test -- --browsers Chrome,Firefox

          # Allow writing test/output.html
          sudo chmod 777 test
          # To debug, run `./test/run.sh -d`
          npm run test:headless
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "sebastien.jourdain@kitware.com"
          npm run semantic-release
      - name: Publish docs
        if: github.ref == 'refs/heads/master'
        env:
          GIT_PUBLISH_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Kitware/itk-vtk-viewer.git
        run: npm run doc:publish
